character:
  name: Kirby
  group_name: Kirby

generation:
  output_dir: /app/output_media
  generation_type_weights:
    text2image2video: 1
    text2longvideo: 1

social_media:
  default_hashtags:
    - kirby
    - mediaoverload

  platforms:
    instagram_graph:
      config_folder_path: /app/configs/social_media/credentials/kirby
      prefix: ""
      enabled: true

    facebook:
      config_folder_path: /app/configs/social_media/credentials/kirby
      prefix: ""
      enabled: true

    youtube:
      config_folder_path: /app/configs/social_media/credentials/kirby
      prefix: ""
      enabled: true

    twitter:
      config_folder_path: /app/configs/social_media/credentials/kirby
      prefix: ""
      enabled: true
