# Wobbuffet 角色配置
character:
  name: waddledee
  group_name: Kirby
  
generation:
  output_dir: /app/output_image
  workflow_path: /app/configs/workflow/nova-anime-xl.json
  similarity_threshold: 0.6
  generation_type: text2img
  
  # 提示詞生成方法的權重配置
  prompt_method_weights:
    arbitrary: 0.1
    news: 0.9
    
  # 圖片系統提示的權重配置  
  image_system_prompt_weights:
    unbelievable_world_system_prompt: 0.1
    stable_diffusion_prompt: 0.7
    buddhist_combined_image_system_prompt: 0.2
  style: minimalism style with pure background

social_media:
  default_hashtags:
    - waddledee
  platforms:
    instagram:
      config_folder_path: /app/configs/social_media/ig/waddledee
      enabled: false

additional_params:
  images_per_description: 10
  is_negative: false 